// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaDrDOsNdwT6j-mHRNijEXvu5XLuZyhpM',
    appId: '1:217497928723:web:12b34da395255db0912be6',
    messagingSenderId: '217497928723',
    projectId: 'first-app-ff7b2',
    authDomain: 'first-app-ff7b2.firebaseapp.com',
    databaseURL:
        'https://first-app-ff7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-ff7b2.appspot.com',
    measurementId: 'G-W60WTVHMF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzBk1uyn-FTTiVJd7Et4PLa4P9jvGfu8',
    appId: '1:217497928723:android:785edfeec8cb9fc9912be6',
    messagingSenderId: '217497928723',
    projectId: 'first-app-ff7b2',
    databaseURL:
        'https://first-app-ff7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-ff7b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYfDC5DUjgbeRF2BZ2nW6gEfB5v2GbT2o',
    appId: '1:217497928723:ios:4ec021c41278b367912be6',
    messagingSenderId: '217497928723',
    projectId: 'first-app-ff7b2',
    databaseURL:
        'https://first-app-ff7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-ff7b2.appspot.com',
    iosBundleId: 'com.example.firebaseDaftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYfDC5DUjgbeRF2BZ2nW6gEfB5v2GbT2o',
    appId: '1:217497928723:ios:3a5901b36b287cd3912be6',
    messagingSenderId: '217497928723',
    projectId: 'first-app-ff7b2',
    databaseURL:
        'https://first-app-ff7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-ff7b2.appspot.com',
    iosBundleId: 'com.example.firebaseDaftarBelanja.RunnerTests',
  );
}
